// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kangla_backend.Model;

#nullable disable

namespace kangla_backend.Migrations
{
    [DbContext(typeof(WateringContext))]
    [Migration("20240705140220_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("kangla_backend.Model.WateringDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WaterNow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WateringDurationSetting")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WateringIntervalSetting")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WateringDevices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Deleted = false,
                            Description = "My device description",
                            Location = "My location",
                            Name = "My device",
                            Notes = "My notes",
                            WaterNow = false,
                            WateringDurationSetting = 0,
                            WateringIntervalSetting = 0
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Deleted = false,
                            Description = "My device description 2",
                            Location = "My location 2",
                            Name = "My device 2",
                            Notes = "My notes 2",
                            WaterNow = false,
                            WateringDurationSetting = 0,
                            WateringIntervalSetting = 0
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Deleted = false,
                            Description = "My device description 3",
                            Location = "My location 3",
                            Name = "My device 3",
                            Notes = "My notes 3",
                            WaterNow = false,
                            WateringDurationSetting = 0,
                            WateringIntervalSetting = 0
                        });
                });

            modelBuilder.Entity("kangla_backend.Model.WateringEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SoilHumidity")
                        .HasColumnType("REAL");

                    b.Property<int>("WateringDeviceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WateringDeviceId");

                    b.ToTable("WateringEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTime = new DateTime(2024, 7, 1, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Duration = 10,
                            SoilHumidity = 0.40000000000000002,
                            WateringDeviceId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateTime = new DateTime(2024, 7, 2, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 15,
                            SoilHumidity = 0.34999999999999998,
                            WateringDeviceId = 2
                        },
                        new
                        {
                            Id = 3,
                            DateTime = new DateTime(2024, 7, 3, 7, 45, 0, 0, DateTimeKind.Unspecified),
                            Duration = 12,
                            SoilHumidity = 0.41999999999999998,
                            WateringDeviceId = 1
                        },
                        new
                        {
                            Id = 4,
                            DateTime = new DateTime(2024, 7, 4, 6, 50, 0, 0, DateTimeKind.Unspecified),
                            Duration = 8,
                            SoilHumidity = 0.38,
                            WateringDeviceId = 3
                        },
                        new
                        {
                            Id = 5,
                            DateTime = new DateTime(2024, 7, 5, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Duration = 20,
                            SoilHumidity = 0.33000000000000002,
                            WateringDeviceId = 2
                        });
                });

            modelBuilder.Entity("kangla_backend.Model.WateringEvent", b =>
                {
                    b.HasOne("kangla_backend.Model.WateringDevice", "WateringDevice")
                        .WithMany("WateringEvents")
                        .HasForeignKey("WateringDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WateringDevice");
                });

            modelBuilder.Entity("kangla_backend.Model.WateringDevice", b =>
                {
                    b.Navigation("WateringEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
