// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kangla_backend.Model;

#nullable disable

namespace kangla_backend.Migrations
{
    [DbContext(typeof(WateringContext))]
    partial class WateringContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("kangla_backend.Model.HumidityMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("SoilHumidity")
                        .HasColumnType("REAL");

                    b.Property<int>("WateringDeviceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WateringDeviceId");

                    b.ToTable("HumidityMeasurements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTime = new DateTime(2024, 7, 6, 6, 0, 0, 0, DateTimeKind.Utc),
                            SoilHumidity = 45.200000000000003,
                            WateringDeviceId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateTime = new DateTime(2024, 7, 6, 7, 0, 0, 0, DateTimeKind.Utc),
                            SoilHumidity = 44.799999999999997,
                            WateringDeviceId = 1
                        },
                        new
                        {
                            Id = 3,
                            DateTime = new DateTime(2024, 7, 6, 8, 0, 0, 0, DateTimeKind.Utc),
                            SoilHumidity = 44.0,
                            WateringDeviceId = 1
                        },
                        new
                        {
                            Id = 4,
                            DateTime = new DateTime(2024, 7, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            SoilHumidity = 43.5,
                            WateringDeviceId = 1
                        },
                        new
                        {
                            Id = 5,
                            DateTime = new DateTime(2024, 7, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            SoilHumidity = 43.0,
                            WateringDeviceId = 1
                        },
                        new
                        {
                            Id = 6,
                            DateTime = new DateTime(2024, 7, 6, 6, 0, 0, 0, DateTimeKind.Utc),
                            SoilHumidity = 52.100000000000001,
                            WateringDeviceId = 2
                        },
                        new
                        {
                            Id = 7,
                            DateTime = new DateTime(2024, 7, 6, 7, 0, 0, 0, DateTimeKind.Utc),
                            SoilHumidity = 51.799999999999997,
                            WateringDeviceId = 2
                        },
                        new
                        {
                            Id = 8,
                            DateTime = new DateTime(2024, 7, 6, 8, 0, 0, 0, DateTimeKind.Utc),
                            SoilHumidity = 51.399999999999999,
                            WateringDeviceId = 2
                        },
                        new
                        {
                            Id = 9,
                            DateTime = new DateTime(2024, 7, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            SoilHumidity = 51.0,
                            WateringDeviceId = 2
                        },
                        new
                        {
                            Id = 10,
                            DateTime = new DateTime(2024, 7, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            SoilHumidity = 50.600000000000001,
                            WateringDeviceId = 2
                        },
                        new
                        {
                            Id = 11,
                            DateTime = new DateTime(2024, 7, 6, 6, 0, 0, 0, DateTimeKind.Utc),
                            SoilHumidity = 60.5,
                            WateringDeviceId = 3
                        },
                        new
                        {
                            Id = 12,
                            DateTime = new DateTime(2024, 7, 6, 7, 0, 0, 0, DateTimeKind.Utc),
                            SoilHumidity = 60.0,
                            WateringDeviceId = 3
                        },
                        new
                        {
                            Id = 13,
                            DateTime = new DateTime(2024, 7, 6, 8, 0, 0, 0, DateTimeKind.Utc),
                            SoilHumidity = 59.600000000000001,
                            WateringDeviceId = 3
                        },
                        new
                        {
                            Id = 14,
                            DateTime = new DateTime(2024, 7, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            SoilHumidity = 59.200000000000003,
                            WateringDeviceId = 3
                        },
                        new
                        {
                            Id = 15,
                            DateTime = new DateTime(2024, 7, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            SoilHumidity = 58.899999999999999,
                            WateringDeviceId = 3
                        });
                });

            modelBuilder.Entity("kangla_backend.Model.WateringDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WaterNow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WateringDurationSetting")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WateringIntervalSetting")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WateringDevices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Deleted = false,
                            Description = "First watering device",
                            DeviceToken = "abcdefghi0",
                            Location = "Garden",
                            Name = "Device 1",
                            Notes = "Needs regular maintenance",
                            WaterNow = false,
                            WateringDurationSetting = 5,
                            WateringIntervalSetting = 30
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Deleted = false,
                            Description = "Second watering device",
                            DeviceToken = "abcdefghi1",
                            Location = "Greenhouse",
                            Name = "Device 2",
                            Notes = "Check humidity levels",
                            WaterNow = true,
                            WateringDurationSetting = 4,
                            WateringIntervalSetting = 20
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Deleted = false,
                            Description = "Third watering device",
                            DeviceToken = "abcdefghi2",
                            Location = "Front Yard",
                            Name = "Device 3",
                            Notes = "Monitor water usage",
                            WaterNow = false,
                            WateringDurationSetting = 3,
                            WateringIntervalSetting = 25
                        });
                });

            modelBuilder.Entity("kangla_backend.Model.WateringEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<int>("WateringDeviceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WateringDeviceId");

                    b.ToTable("WateringEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            End = new DateTime(2024, 7, 6, 8, 5, 0, 0, DateTimeKind.Utc),
                            Start = new DateTime(2024, 7, 6, 8, 0, 0, 0, DateTimeKind.Utc),
                            WateringDeviceId = 1
                        },
                        new
                        {
                            Id = 2,
                            End = new DateTime(2024, 7, 7, 8, 5, 0, 0, DateTimeKind.Utc),
                            Start = new DateTime(2024, 7, 7, 8, 0, 0, 0, DateTimeKind.Utc),
                            WateringDeviceId = 1
                        },
                        new
                        {
                            Id = 3,
                            End = new DateTime(2024, 7, 6, 9, 4, 0, 0, DateTimeKind.Utc),
                            Start = new DateTime(2024, 7, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            WateringDeviceId = 2
                        },
                        new
                        {
                            Id = 4,
                            End = new DateTime(2024, 7, 7, 9, 4, 0, 0, DateTimeKind.Utc),
                            Start = new DateTime(2024, 7, 7, 9, 0, 0, 0, DateTimeKind.Utc),
                            WateringDeviceId = 2
                        },
                        new
                        {
                            Id = 5,
                            End = new DateTime(2024, 7, 6, 10, 3, 0, 0, DateTimeKind.Utc),
                            Start = new DateTime(2024, 7, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            WateringDeviceId = 3
                        },
                        new
                        {
                            Id = 6,
                            End = new DateTime(2024, 7, 7, 10, 3, 0, 0, DateTimeKind.Utc),
                            Start = new DateTime(2024, 7, 7, 10, 0, 0, 0, DateTimeKind.Utc),
                            WateringDeviceId = 3
                        });
                });

            modelBuilder.Entity("kangla_backend.Model.HumidityMeasurement", b =>
                {
                    b.HasOne("kangla_backend.Model.WateringDevice", "WateringDevice")
                        .WithMany("HumidityMeasurement")
                        .HasForeignKey("WateringDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WateringDevice");
                });

            modelBuilder.Entity("kangla_backend.Model.WateringEvent", b =>
                {
                    b.HasOne("kangla_backend.Model.WateringDevice", "WateringDevice")
                        .WithMany("WateringEvents")
                        .HasForeignKey("WateringDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WateringDevice");
                });

            modelBuilder.Entity("kangla_backend.Model.WateringDevice", b =>
                {
                    b.Navigation("HumidityMeasurement");

                    b.Navigation("WateringEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
