// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kangla_backend.Model;

#nullable disable

namespace kangla_backend.Migrations
{
    [DbContext(typeof(WateringContext))]
    partial class WateringContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("kangla_backend.Model.WateringDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastWatering")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<double>("SoilHumidity")
                        .HasColumnType("REAL");

                    b.Property<bool>("WaterNow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WateringDuration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WateringInterval")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WateringDevices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Deleted = false,
                            Description = "My device description",
                            LastWatering = new DateTime(2024, 7, 4, 14, 46, 22, 852, DateTimeKind.Local).AddTicks(7021),
                            Location = "My location",
                            Name = "My device",
                            Notes = "My notes",
                            SoilHumidity = 0.5,
                            WaterNow = false,
                            WateringDuration = 3,
                            WateringInterval = 300
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Deleted = false,
                            Description = "My device description 2",
                            LastWatering = new DateTime(2024, 7, 4, 14, 46, 22, 852, DateTimeKind.Local).AddTicks(7073),
                            Location = "My location 2",
                            Name = "My device 2",
                            Notes = "My notes 2",
                            SoilHumidity = 0.5,
                            WaterNow = false,
                            WateringDuration = 3,
                            WateringInterval = 300
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Deleted = false,
                            Description = "My device description 3",
                            LastWatering = new DateTime(2024, 7, 4, 14, 46, 22, 852, DateTimeKind.Local).AddTicks(7076),
                            Location = "My location 3",
                            Name = "My device 3",
                            Notes = "My notes 3",
                            SoilHumidity = 0.5,
                            WaterNow = false,
                            WateringDuration = 3,
                            WateringInterval = 300
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
