@kangla_backend_HostAddress = http://localhost:5159

GET {{kangla_backend_HostAddress}}/WateringDevices/
Accept: application/json
###

GET {{kangla_backend_HostAddress}}/WateringDevices/1
Accept: application/json
###


