name: Build and push to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    if: |
      github.event_name == 'workflow_dispatch' ||
      !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            --build-arg ASPNETCORE_ENVIRONMENT=Production \
            --build-arg BUILD_CONFIGURATION=Release \
            --build-arg UID=1001 \
            --build-arg GID=1001 \
            -t ghcr.io/${{ github.repository }}:latest \
            -f ./src/kangla.WebApi/Dockerfile .

      - name: Push image
        run: docker push ghcr.io/${{ github.repository }}:latest
